[project]
name = "rainwave-discord-streamer"
version = "2025.0"
description = "Stream Rainwave radio to Discord"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "discord-py[voice]>=2.6.4",
    "notch>=2025.2",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
    "ty>=0.0.9",
]

[tool.ruff.lint]
select = ["ANN", "E", "F", "FURB", "I", "PERF", "RUF", "S", "UP"]
